
import React from 'react';
import ContentCard, { Content } from './ContentCard';

// Mock data for recommended content
const mockRecommendedContent: Content[] = [
  {
    id: '1',
    title: 'Anthropic Releases Claude 3.5: Sets New Performance Benchmarks',
    summary: 'Anthropic has unveiled Claude 3.5, featuring significant improvements in reasoning, coding, and multimodal understanding. The model outperforms previous versions across all benchmark tests.',
    category: 'AI Research',
    date: 'April 12, 2025',
    authors: ['Anthropic Research Team'],
    isHighlighted: true
  },
  {
    id: '2',
    title: 'Security Vulnerabilities Discovered in Google Gemini Code Generation',
    summary: 'Researchers have identified potential security flaws in code generated by Google\'s Gemini model. The vulnerability could lead to unintended system access when implemented without review.',
    category: 'Security',
    date: 'April 11, 2025',
    authors: ['Security Research Group'],
    isHighlighted: true
  },
  {
    id: '3',
    title: 'Training Large Language Models with Synthetic Data: A Comparative Study',
    summary: 'This paper explores the effectiveness of synthetic data in training LLMs, comparing performance metrics across models trained on different ratios of synthetic to real data.',
    category: 'NLP',
    date: 'April 10, 2025',
    authors: ['Zhang, L.', 'Johnson, K.', 'Patel, S.'],
    citations: 42
  },
  {
    id: '4',
    title: 'Vision Transformers for Real-time Object Detection in Autonomous Vehicles',
    summary: 'A novel approach to implementing Vision Transformers (ViT) for high-speed, low-latency object detection specifically optimized for autonomous driving systems.',
    category: 'Computer Vision',
    date: 'April 8, 2025',
    authors: ['Lee, J.', 'Garcia, M.', 'Kim, H.'],
    citations: 37
  },
  {
    id: '5',
    title: 'Efficient Prompt Engineering Techniques for Domain-Specific Applications',
    summary: 'This comprehensive guide presents systematic approaches to prompt engineering for specialized domains like healthcare, finance, and legal applications.',
    category: 'NLP',
    date: 'April 7, 2025',
    authors: ['Rodriguez, A.', 'Smith, T.'],
    citations: 19
  },
  {
    id: '6',
    title: 'Multi-Agent Reinforcement Learning for Robotic Coordination',
    summary: 'A framework for training multiple robotic agents to collaborate efficiently on complex physical tasks through distributed reinforcement learning algorithms.',
    category: 'Robotics',
    date: 'April 6, 2025',
    authors: ['Wong, R.', 'Ivanov, A.', 'Müller, K.'],
    citations: 28
  }
];

const RecommendedFeed: React.FC = () => {
  // First two are highlighted (today's headlines)
  const headlines = mockRecommendedContent.slice(0, 2);
  const regularContent = mockRecommendedContent.slice(2);

  return (
    <div className="space-y-6">
      {headlines.length > 0 && (
        <div>
          <h2 className="text-xl font-bold mb-3">Today's Headlines</h2>
          <div className="grid gap-4 md:grid-cols-2">
            {headlines.map(content => (
              <ContentCard key={content.id} content={content} />
            ))}
          </div>
        </div>
      )}
      
      <div>
        <h2 className="text-xl font-bold mb-3">Recommended For You</h2>
        <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
          {regularContent.map(content => (
            <ContentCard key={content.id} content={content} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default RecommendedFeed;
